### PR TITLE
Test out multicore building

### PR DESCRIPTION
**Pull request by nolim1t**
Test out multicore building (Thanks @AaronDewes)

### CODE REVIEW

**Comment by AaronDewes** [comment]
Can you also use a matrix? https://github.com/lncm/docker-lnd/blob/master/.github/workflows/on-tag.yml#L23 That would probably make builds even faster because they run in parallel

**Comment by nolim1t** [comment]
> Can you also use a matrix? https://github.com/lncm/docker-lnd/blob/master/.github/workflows/on-tag.yml#L23 That would probably make builds even faster because the architectures are being built each on its own runner/VM/whatever (idk how GitHub actions work behind the scenes)

That could be looked at eventually but right now it would require a bit of changes

**Comment by nolim1t** [comment]
Another thing I'm keeping in mind is that I also want the images to be built on other platforms too in the spirit of decentralization.

I'm also using gitlab actions too and also the gitlab container registry.

Will look at GitHub container registry when it seems working (so far it doesn't seem to work as documented the last time I tried)

**Comment by nolim1t** [comment]
This seems to be a lot faster

**Pull request merged**
