### PR TITLE
Update to latest Tor

### PR DESCRIPTION
**Pull request by AaronDewes**
Tor 0.4.7.13 contains multiple improvements and a security fix, so it would be great if you could merge this soon.

### CODE REVIEW

**Comment by nolim1t** [comment]
Thanks @AaronDewes

**Comment by nolim1t** [comment]
v0.4.7.13 doesnt exist

**Comment by AaronDewes** [comment]
Tor versions don't use the v prefix, you need to remove the v from the tag so it gets built properly.

**Comment by AaronDewes** [comment]
I created the correct tag now, I hope that's okay

**Comment by nolim1t** [comment]
All good as long as nothing new breaks

**Pull request merged**
